
## CreateUser
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
  "name": "Vini Batista",
  "email": "vini@email.com",
  "password": "pass@123",
  "cep": "01153000"
}
###

## Login
# @name login
POST http://localhost:8080/auth/login HTTP/1.1
content-type: application/json

{
  "email": "vinig@email.com",
  "password": "pass@1234"
}
###
@token = {{login.response.body.access_token}}

## UpdateUser
PATCH http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Vini Gomes",
  "email": "vinig@email.com",
  "cep": "88132243"
}
###

## GetUserByID
GET http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

## DeleteUser
DELETE http://localhost:8080/user HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
####

## FindManyUsers
GET http://localhost:8080/user/list-all HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

## UpdateUserPassword
PATCH http://localhost:8080/user/password HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "password": "pass@1234",
  "old_password": "pass@123"
}
###

### Categories

## CreateCategory
POST http://localhost:8080/category HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "Samsung"
}
###

## FindManyCategories
# @name find_categories
GET http://localhost:8080/categories HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

###
# O código abaixo salva o ID da primeira categoria encontrada na variável 'category_id'
###
@category_id = {{find_categories.response.body.categories.[0].id}}


### Products

## CreateProduct
POST http://localhost:8080/product HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "title": "Samsung",
  "description": "wewewe",
  "categories": ["{{category_id}}"],
  "price": 39900
}
###

## UpdateProduct
PATCH http://localhost:8080/product/37545729-e891-40b5-946c-8e7d55bd686b HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "categories": ["07145e70-2a8e-4f71-9165-f0d450afa524"]
}
###

## DeleteProduct
DELETE http://localhost:8080/product/f720e1ce-cb88-4f72-a765-0250c1a525e3 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}
###

## FindManyProducts
GET http://localhost:8080/product HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "categories": ["{{category_id}}"]
}